name: Publish and Upload to S3

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Adjust to your .NET Core version

    - name: Publish .NET Project
      run: dotnet publish -c Release -o ./output

    - name: Zip output files
      run: zip -r output.zip ./output

    - name: Upload to S3
      env:
        AWS_REGION: us-west-2  # Replace with your region
        S3_BUCKET: your-bucket-name  # Replace with your S3 bucket name
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp output.zip s3://$S3_BUCKET/versions/RSABot.zip
